//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.UploadedFiles = new HashSet<UploadedFile>();
        }
    
        public int IDStudent { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Residence must be 50 characters max!")]
        public string Residence { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "University must be 100 characters max!")]
        public string University { get; set; }
        [Required]
        [MaxLength(100, ErrorMessage = "Email must be 100 characters max!")]
        public string Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedFile> UploadedFiles { get; set; }
    }
}
